// <auto-generated />
using System;
using AliensAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AliensAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AliensAPI.Models.AlienModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("CurrentArrival")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CurrentDeparture")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentPlanetId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<string>("IId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NativePlanetId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OriginArrival")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OriginDeparture")
                        .HasColumnType("datetime2");

                    b.Property<int>("OriginPlanetId")
                        .HasColumnType("int");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CurrentPlanetId");

                    b.HasIndex("NativePlanetId");

                    b.HasIndex("OriginPlanetId");

                    b.ToTable("Aliens");
                });

            modelBuilder.Entity("AliensAPI.Models.PlanetModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NativeSpecies")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Planets");
                });

            modelBuilder.Entity("AliensAPI.Models.PowerModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Powers");
                });

            modelBuilder.Entity("AliensPowers", b =>
                {
                    b.Property<int>("AlienId")
                        .HasColumnType("int");

                    b.Property<int>("PowerId")
                        .HasColumnType("int");

                    b.HasKey("AlienId", "PowerId");

                    b.HasIndex("PowerId");

                    b.ToTable("AliensPowers");
                });

            modelBuilder.Entity("AliensAPI.Models.AlienModel", b =>
                {
                    b.HasOne("AliensAPI.Models.PlanetModel", "CurrentPlanet")
                        .WithMany("CurrentTourists")
                        .HasForeignKey("CurrentPlanetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AliensAPI.Models.PlanetModel", "NativePlanet")
                        .WithMany("CurrentNativePopulation")
                        .HasForeignKey("NativePlanetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AliensAPI.Models.PlanetModel", "OriginPlanet")
                        .WithMany("CurrentImmigrantPopulation")
                        .HasForeignKey("OriginPlanetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurrentPlanet");

                    b.Navigation("NativePlanet");

                    b.Navigation("OriginPlanet");
                });

            modelBuilder.Entity("AliensPowers", b =>
                {
                    b.HasOne("AliensAPI.Models.AlienModel", null)
                        .WithMany()
                        .HasForeignKey("AlienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AliensAPI.Models.PowerModel", null)
                        .WithMany()
                        .HasForeignKey("PowerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AliensAPI.Models.PlanetModel", b =>
                {
                    b.Navigation("CurrentImmigrantPopulation");

                    b.Navigation("CurrentNativePopulation");

                    b.Navigation("CurrentTourists");
                });
#pragma warning restore 612, 618
        }
    }
}
